---
# This playbook deploys the whole application stack in this site.  

- name: Apply Common configuration to all nodes
  hosts: lamp-servers
  remote_user: root

  roles:
    - common

- name: Configure and deploy the Webservers and application code
  hosts: lamp-servers
  remote_user: root

  roles:
    - web

- name: Deploy MySQL and configure the Databases
  hosts: lamp-servers
  remote_user: root

  roles:
    - db
