---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: centos
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
